name: fairness-comparison
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - jupyter_contrib_nbextensions
  - pip
  - python=3.6.8
  - seaborn>=0.11.0
  - pip:
    - fairness==0.1.8
